### ISSUE TITLE
手柄兼容性问题

### ISSUE THREAD

**Issue by VG666** [Geocld/XStreaming#14]
xbox手柄连接上手机错位，并且有部分按键用不了，还有主菜单是否可以新增使用手柄进行控制的功能

**Comment by fejich** [comment]
XBOX 手柄出民很多代
最好用 GamePad Tester 之类的软件
看看按键不正常的手柄
是什么识别码，方便排查

**Comment by Geocld** [comment]
Fixed in [v0.3.1](https://github.com/Geocld/XStreaming/releases/tag/v0.3.1).
