### ISSUE TITLE
断开后重连不上

### ISSUE THREAD

**Issue by www2790** [Geocld/XStreaming#16]
故障复现：
1、手机app连接xbox，已成功串流到画面。
2、想起bsp-d8蓝牙手柄未连接，手柄打开后app闪退。
3、打开app再次连接Xbox，一直显示正在连接，最后提示：fail:streaming failed:Agent:ServerNeverRegistered:Server never registered with service:State Waiting For Server To Register
只有把xbox主机关闭重启，才能再进行连接。

**Comment by Geocld** [comment]
这是Xbox的API直接无法唤醒报的错，这个在串流主机时会出现这种错误，这里是[相同的情况](https://github.com/unknownskl/greenlight/issues/798)，且没有办法完全解决，只能通过手动按电源键唤醒主机或重启主机解决，后续这类错误我会优化错误输出
