### ISSUE TITLE
hi 作者大大您好 想问下可以用uu加速器加速吗 

### ISSUE THREAD

**Issue by yangdihui** [Geocld/XStreaming#17]
用XStreaming之前我用的是狐猴浏览器配合油猴插件 然后这个浏览器应该是改包版 uu加速器可以识别为官方的app所以可以直接加速

**Comment by yangdihui** [comment]
内置的免代理延迟100左右有点高 想问下有没有办法用uu加速器加速

**Comment by Geocld** [comment]
@yangdihui release里的apk有一个带fake字段的，用的是com.gamepass的包名，支持uu加速器识别

https://github.com/Geocld/XStreaming/releases/download/v0.2.0/XStreaming-fake-0.2.0.apk

**Comment by yangdihui** [comment]
好的好的 感谢大大！
