### ISSUE TITLE
免代理地区设置确定有效吗

### ISSUE THREAD

**Issue by N0p1an** [Geocld/XStreaming#18]
免代理地区设置确定有效吗，无论切换到哪，相比网页（插件美区）都缺少游戏
![146d72219a80b44adbf149fc6441d95](https://github.com/Geocld/XStreaming/assets/175293642/0a161d33-fab4-4252-afbb-09184c661f85)

**Comment by Geocld** [comment]
@N0p1an 如果你在中国地区，而且没有开任何代理，能打开云游戏，就说明免代理已生效，至于缺少游戏，用的是微软官方的API接口，游戏数据少了也是正常情况。
