### ISSUE TITLE
[GamePad Mapping] XBOX Button Mapping Problem

### ISSUE THREAD

**Issue by mumiao2000** [Geocld/XStreaming#2]
My cell phone is MEIZU 20, and gamepad is Gamesir X2s Type-C.

So the issue is X2s has no XBOX button, and I want to map HOME button of the controller to XBOX button. However, it doesn't work.

**Comment by Geocld** [comment]
@mumiao2000 Some gamepad does not have home button in webview，in xstreaming you can use menu+view button to call Home button feature in default.

**Comment by mumiao2000** [comment]
Thank you, get it!
