### ISSUE TITLE
建议增加检查更新功能

### ISSUE THREAD

**Issue by chairzzz** [Geocld/XStreaming#20]
谢谢作者花那么多时间给大家实现了这个免费的串流app

反馈个建议，因为现在还在开发阶段，更新会比较多。
可以在app里面增加一个检查更新的功能，直接从github release里面下载新版本的apk

辛苦作者了！

**Comment by Geocld** [comment]
Supported at [v1.0.0](https://github.com/Geocld/XStreaming/releases/tag/v1.0.0)
