### ISSUE TITLE
关于xsx 内网串流 码流疑问

### ISSUE THREAD

**Issue by Xiepoder** [Geocld/XStreaming#22]
xbox 串流实际最高码率只有 15Mbps

这个有办法 提高嘛？听说是微软自身的限制

**Comment by fejich** [comment]
微软的限制
自从 XS 系列出来后就这样子了
xCloud 云游戏也是这个样
应该是程序员为了省事，用同一套代码写死了码率

**Comment by Xiepoder** [comment]
> 微软的限制 自从 XS 系列出来后就这样子了 xCloud 云游戏也是这个样 应该是程序员为了省事，用同一套代码写死了码率
可惜了 内网环境呢
