### ISSUE TITLE
希望加入电视操作逻辑

### ISSUE THREAD

**Issue by PandaChung** [Geocld/XStreaming#23]
目前的客户端在手机运行良好，可以无法在电视端正常操作，希望能加入电视遥控操作支持！谢谢！

**Comment by Geocld** [comment]
[v1.0.0](https://github.com/Geocld/XStreaming/releases/tag/v1.0.0)使用了全新的UI交互，已支持外设操作。

**Comment by PandaChung** [comment]
感谢感谢！
