### ISSUE TITLE
普通版和fake版什么区别？

### ISSUE THREAD

**Issue by Golubb** [Geocld/XStreaming#24]
release里有两个下载，一个普通，一个文件名带fake，什么区别啊？

**Comment by Geocld** [comment]
@Golubb fake版包名使用了com.gamepass，可以让主流加速器如uu加速器识别为官方gamepass应用，从而达到加速游戏的效果

**Comment by heximing** [comment]
建议把这个issue置顶，或者在简介，或者在release，说明一下fake是什么意思。
