### ISSUE TITLE
云游戏和小鸡手柄存在兼容性问题

### ISSUE THREAD

**Issue by zgd04** [Geocld/XStreaming#27]
云游戏和小鸡手柄存在兼容性问题，详细如下

硬件：小鸡G8手柄，小鸡X2S手柄，PS4手柄，红米K30 5G手机 MiUI 13.0.3
软件：XStreaming 0.3.1（fake版表现相同），Xbox game pass Android app 和game pass 网页。

具体问题：
小鸡手柄使用Xstreamng，按下LT键（FPS一般是开镜瞄准）会触发两次抬枪瞄准的动作。
保持LT键按下，其他键不动，人物保持瞄准的动作，这是正常的。但是只要移动LS或者RS就会触发快速连续多次的瞄准动作，准星一跳一跳的。

PS4手柄使用Xstreaming正常，使用xboxgame pass app和网页正常。

小鸡手柄使用xbox game pass android app 和game pass 网页，正常。

Ps：
1.小鸡手柄LT键没有开启连击模式，都是单发。
2.XStreaming 手柄内核选择的native，选web，则云游戏无法识别小鸡手柄。
![Uploading 小鸡+game pass 网页.gif…]()
![Uploading 小鸡+Xstreaming.gif…]()

**Comment by zgd04** [comment]
![小鸡+game pass 网页](https://github.com/user-attachments/assets/d538d860-7c28-4ac1-9c2e-0b7869926762)
![小鸡+Xstreaming](https://github.com/user-attachments/assets/350a991b-12a2-4f51-a773-3e97b91032bc)

**Comment by zgd04** [comment]
第一个是小鸡+game pass网页，第二个是小鸡+Streaming

**Comment by Geocld** [comment]
前几天我已经发现这个问题了，是由于LT/RT处理逻辑问题导致的，目前代码已经修改，等下一个版本修复

**Comment by zgd04** [comment]
非常感谢，下个版本应该也会出fake版的吧，开加速器还是有点作用的。Xstreaming 比 game pass app香太多了。加油

**Comment by Geocld** [comment]
Fixed in [v1.0.0](https://github.com/Geocld/XStreaming/releases/tag/v1.0.0)

**Comment by zgd04** [comment]
RT在连续快速按下的情况下，很容易丢失触发。10次触发3次这样。
看动图，前面是xbox game pass网页，后边是Xstreaming。还是小鸡手柄。麻烦楼主看一下

![GIF1·](https://github.com/user-attachments/assets/c42cbcca-c048-4903-8f32-44a65b2dd38c)

**Comment by Geocld** [comment]
@zgd04 是否升级到1.0.0，其他手柄是否有问题？

**Comment by zgd04** [comment]
版本1.0.0。我只有小鸡手柄，0.3.1版本存在LT连续触发问题。1.0.0版本LT问题修复，但是有RT丢失触发问题。还有一个ps4手柄，ps手柄在0.3.1上就不存在任何问题，1.0.0我就没有测试。测的是fake版，普通版本大概也存在同样问题吧，我也没有做测试。

**Comment by Geocld** [comment]
@zgd04 fake和普通版的实现代码完全一样，我大概知道什么原因了，今天或明天我会发个版本来优化这个机制

**Comment by zgd04** [comment]
太强了，我第一时间测试反馈。

**Comment by Geocld** [comment]
@zgd04 [1.1.0](https://github.com/Geocld/XStreaming/releases/tag/v1.1.0)已经发布，对按键延迟做了优化，升级试试

**Comment by zgd04** [comment]
玩了一个小时，完美解决。
