### ISSUE TITLE
0.31版的手柄震动导致app闪退

### ISSUE THREAD

**Issue by ken5457** [Geocld/XStreaming#28]
0.31版，手机是vivo x fold3，手柄是小鸡G8+，如果开启手柄震动，进云游戏后如果游戏中遇到震动，app立刻闪退。
在设置里的debug选项测试手柄震动，也是一样，点击测试app立刻闪退。
换佰世派D11手柄测试，则表现为震动失效（有时候有效，有时候失效），但app不闪退。

回退到0.30版，小鸡G8+震动大部分时候正常，偶尔震动失效，但不闪退。

相对来说0.30版的震动更稳定。

手机机身震动，在debug震动测试里都正常，不管是0.31版还是0.30版。

最后非常感谢作者，streaming是绝佳的app！xbox云游戏我已经用它完全取代了之前狐猴浏览器的脚本大法，尤其是震动体验比脚本大法好得多，希望这个app能越做越好！

**Comment by Geocld** [comment]
@ken5457 谢谢反馈这么详细的测试记录，看来这个是个别组合有问题，可不可以尝试在手机上找下闪退错误报告，这样我比较好定位问题

**Comment by Geocld** [comment]
@ken5457 另外d11的振动失效是使用哪个模式（指示灯是什么颜色）？

**Comment by ken5457** [comment]
错误报告文件的手机路径在哪里找呢？我可以试着找找看。

另外，D11震动用的是紫灯模式，就是是模拟xbox或ds4手柄的那个模式。

**Comment by Geocld** [comment]
@ken5457 如果没有官方的应用可以查看可以安装一个MatLog，尝试用这个应用获取闪退的堆栈信息，如果能拿到日志更好了，我就不用到处找真机测试了

**Comment by ken5457** [comment]
@Geocld vivo系统的官方日志功能好像抓不到app的崩溃日志，回头我装个Matlog试试看

**Comment by Geocld** [comment]
@ken5457 已经使用y700+米墨s3复现bug并已定位，即将在下一个版本修复。

**Comment by ken5457** [comment]
@Geocld 赞！效率真高👍🏻

**Comment by Geocld** [comment]
Fixed in [v1.0.0](https://github.com/Geocld/XStreaming/releases/tag/v1.0.0)
