### ISSUE TITLE
考虑开发ios端吗

### ISSUE THREAD

**Issue by theslugger** [Geocld/XStreaming#3]
期待ios端的加入

**Comment by arcsinw** [comment]
看代码是react-native写的，能编译出ios的包，但上架iOS需要账号

**Comment by Geocld** [comment]
待Android功能完善稳定后会支持iOS，目前90%的代码两个端是共用的

**Comment by chairzzz** [comment]
如果等不及，而且有mac电脑可以自己下一个xcode，用源码可以直接编译一个安装到自己手机(不需要开发者账号）
