### ISSUE TITLE
[BUG] Android14 Themed icon适配问题

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [Geocld/XStreaming#32]
如图，在关闭主题图标功能后软件图标显示正常，但打开后会出现适配问题
![Screenshot_20240806-023711.png](https://github.com/user-attachments/assets/0ae74b8d-f4cb-497e-bc76-bdae9a0df4b9)

![Screenshot_20240806-023717.png](https://github.com/user-attachments/assets/5109ddef-d624-4989-bf87-f27f8dcb28cf)

**Comment by Geocld** [comment]
谢谢反馈，[v1.1.0](https://github.com/Geocld/XStreaming/releases/tag/v1.1.0)已修复。
