### ISSUE TITLE
云游戏界面优化

### ISSUE THREAD

**Issue by youngnet** [Geocld/XStreaming#36]
<img width="316" alt="iShot_2024-08-09_15 45 06" src="https://github.com/user-attachments/assets/f22083af-ac37-4f53-a6e5-57c9b8e94035">
小建议这样空间更大一些看着也更协调

**Comment by youngnet** [comment]
tab居左 右侧搜索

**Comment by Geocld** [comment]
@youngnet 谢谢建议，已经在[v1.1.2](https://github.com/Geocld/XStreaming/releases/tag/v1.1.2)采纳
