### ISSUE TITLE
云游戏打开直接报错400

### ISSUE THREAD

**Issue by lesvate** [Geocld/XStreaming#37]
![Screenshot_2024-08-11-02-05-13-691_com xstreaming](https://github.com/user-attachments/assets/c1988145-2752-4966-b220-0aac10230f25)

**Comment by lesvate** [comment]
版本1.1.1

**Comment by Geocld** [comment]
@lesvate 使用1.0.0是否正常

**Comment by lesvate** [comment]
sorry,会员弄错了，重新买了xgpu就好了，是否在登陆时检查下会员版本，以免像我这样疑惑
