### ISSUE TITLE
似乎无法切换不使用软件内代理

### ISSUE THREAD

**Issue by infinitytom** [Geocld/XStreaming#40]
我用uu加速官方软件几乎每丢包，用fake版的默认代理再开uu没有用，丢包百分之10以上

**Comment by Geocld** [comment]
@infinitytom 应用设置里的代理并没有网络加速功能，只是让你获得xgpu游戏权限，因为xgpu是限制地区访问的。提供fake的目的就是让uu这些主流加速器识别到并且网络加速。

**Comment by Geocld** [comment]
@infinitytom 另外检查下是不是手机里装了两个官方应用，再用fake应用包有可能会导致uu应用识别失败从而加速失败，或者可以尝试先进游戏再加速

**Comment by infinitytom** [comment]
理解了，不过我只下载了官方测试版，uu加速时会询问要打开哪个软件，但在xs软件中选择韩服再进行uu亚洲区加速后仍有丢包，能否像网页版插件那样设置直接关闭代理，因为我在pc上这样做然后直接用uu是有效的,安卓浏览器版的对国产的xinput协议手柄似乎会按键映射错误

**Comment by infinitytom** [comment]
@Geocld 理解了，不过我只下载了官方测试版，uu加速时会询问要打开哪个软件，但在xs软件中选择韩服再进行uu亚洲区加速后仍有丢包，能否像网页版插件那样设置直接关闭代理，因为我在pc上这样做然后直接用uu是有效的,安卓浏览器版的对国产的xinput协议手柄似乎会按键映射错误

**Comment by infinitytom** [comment]
@Geocld 感谢解惑

**Comment by Geocld** [comment]
> @Geocld 理解了，不过我只下载了官方测试版，uu加速时会询问要打开哪个软件，但在xs软件中选择韩服再进行uu亚洲区加速后仍有丢包，能否像网页版插件那样设置直接关闭代理，因为我在pc上这样做然后直接用uu是有效的,安卓浏览器版的对国产的xinput协议手柄似乎会按键映射错误

设置-地区设置选默认就是关闭地区代理了。这个原理跟网页插件是一样的，只是通过修改云游戏api的一个header来实现，理论上并不会对整个网络传输造成影响，出现丢包大概率还是因为加速器的加速代理没有成功

**Comment by infinitytom** [comment]
@Geocld 好像确实，刚刚重新用默认在uu中打开了一次几乎不丢包了，但是之前未成功，将官方软件删除似乎可以保证成功率

**Comment by infinitytom** [comment]
@Geocld 非常感谢解答
