### ISSUE TITLE
安卓7.1.2的电视盒子安装错误

### ISSUE THREAD

**Issue by www2790** [Geocld/XStreaming#41]
已更新webview版本。adb命令安装提示
adb: failed to install aa.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl1599140295.tmp/base.apk (at Binary XML file line #7): Requires newer sdk version #26 (current version is #25)]

**Comment by Geocld** [comment]
精力有限，不打算支持太低版本的系统了，安卓7即使能正常安装，WebView版本也难以支持webrtc标准协议。
