### ISSUE TITLE
云游戏白屏，是连接不上吗？

### ISSUE THREAD

**Issue by WangChun420** [Geocld/XStreaming#46]
代理直连和APP内设置区域都试了，云游戏白屏

**Comment by Geocld** [comment]
@WangChun420 是因为设备系统WebView版本太低了。
检查方法：安卓打开开发者模式-进入开发者选项-查看WebView实现，xstreaming需要91以上的WebView版本才能正常运行串流逻辑。

处理方法：升级WebView，可以直接安装WebView的离线apk，具体可以参考此处文档并下载离线apk：https://github.com/Geocld/XStreaming/tree/main/tools
