### ISSUE TITLE
摇杆有死区

### ISSUE THREAD

**Issue by jsbwyqiwjx** [Geocld/XStreaming#47]
已经将设置里的摇杆死区调至最低0.1但相比xbox game pass软件的云游戏还是有死区

**Comment by Geocld** [comment]
@jsbwyqiwjx 此前版本的死区指的是中心区触发有效区域，最大值边缘在[v1.2.0](https://github.com/Geocld/XStreaming/releases/tag/v1.2.0)可以设置摇杆边缘补偿，如果手柄摇杆最大值达不到期望，可以适当添加补偿。
