### ISSUE TITLE
获取终端的页面，一直转圈显示正在检查登录

### ISSUE THREAD

**Issue by lyz337959725** [Geocld/XStreaming#49]
之前使用呢很正常，有一天突然就不行了，在获取终端的页面，一直转圈显示正在检查登录，需要来回重启两三次设备，才能获取到设备开始链接。

**Comment by Geocld** [comment]
因为微软国内没有服务器，相关接口有时候会有网络卡住的情况，这些都是正常现象，遇到类似的情况切换网络多试几次吧。

**Comment by lyz337959725** [comment]
我开着梯子 也是这样

**Comment by lyz337959725** [comment]
我只要不重启xbox设备，重试几次都是这样 ，只有重启设备才好，而且之前是没有这种现象的

**Comment by Geocld** [comment]
@lyz337959725 获取设备列表跟你的主机开机与否没关系的，设备列表直接请求微软服务器接口获取结果

**Comment by lyz337959725** [comment]
这个我理解，所以遇到这种情况后，我打开微软官方的那个app进行了尝试，官方的那个就可以，我再切回来使用这个还是不行，这个就很纳闷了，网络环境都一样。

**Comment by Geocld** [comment]
[v1.0.4](https://github.com/Geocld/XStreaming/releases/tag/v1.1.4)已优化登录
