### ISSUE TITLE
安卓手柄识别问题

### ISSUE THREAD

**Issue by jinsheMichael** [Geocld/XStreaming#51]
我现在用的设备华为Mate40Pro，另外2个手柄 北通鲲鹏20，Xbox手柄。
震动模式选择native，北通的震动会正常触发。
换成Xbox的话，手机会震动，手柄不会。

**Comment by Geocld** [comment]
手柄振动起始跟安卓设备的内核有关系，如果蓝牙、USB模式手柄都无法振动，将会回退到设备振动。而且xbox手柄协议在安卓内核也有要求，具体参考下图：
![20241015090508](https://github.com/user-attachments/assets/d9a533f9-6d38-455e-86cb-664a910974d4)

如果内核不满足上述要求，那就会出现你所说的xbox手柄无法振动的情况，不管使用什么振动模式。

不过目前也有解决方法，就是让XSt应用强制托管USB连接手柄，目前该功能还在开发，可以在下个版本测试下。

**Comment by Geocld** [comment]
[v1.2.0](https://github.com/Geocld/XStreaming/releases/tag/v1.2.0)已支持usb覆盖驱动模式，无法振动的xbox手柄可以通过有线连接的方式振动

**Comment by anmasiii** [comment]
现在振动是能振动了，但会出现手柄操控失灵
