### ISSUE TITLE
索尼a8f电视

### ISSUE THREAD

**Issue by glming** [Geocld/XStreaming#54]
可以成功安装在索尼a8f电视上，成功登录微软账号，但是启动串流之后就白屏幕，等待5分钟还是这样，反复试了几次都是这样失败。之后同网络环境用手机使用xbox原厂app成功

**Comment by Geocld** [comment]
@glming 这是因为安卓系统webview版本过低导致，XStreaming需要最低版本的webview实现91.xx以上，请查阅下面的文档查看并升级webview:

[低版本安卓无法运行方法](https://github.com/Geocld/XStreaming/blob/main/tools/readme.md)

因为安卓系统的特殊性，并不是所有设备都能顺利升级webview，如果无法升级webview，建议继续使用官方xbox应用。
