### ISSUE TITLE
有没有可能实现指定使用的webview？

### ISSUE THREAD

**Issue by capt-ximao** [Geocld/XStreaming#55]
作者你好，
        我的问题是我的小米电视安装了新版webview
后发现新版的包名和内置的不一样，内置的是com.android.webview，新的是com.google.android.webview。安装新版webview后白屏依旧。
        我猜想是否原因是app默认还是使用了旧版webview。因此，如果由app指定使用新版webview应该可以解决问题。不知安卓机制上是否允许这么干？

**Comment by Geocld** [comment]
@capt-ximao 目前应用级别还无法切换系统级别的webview，我网上搜了下升级webview相关的，下面这个教程可以对你有帮助：
[Android 自带的 WebView 更新](https://gitee.com/akenclub/android-web-view)

**Comment by Anartx** [comment]
> @capt-ximao目前应用级别还无法切换系统级别的webview，我网上搜了下升级webview相关的，下面这个教程可以对你有帮助： [Android自带的WebView更新](https://gitee.com/akenclub/android-web-view)

大佬可以参考一下better xcloud，他进去的时候就有个web切换选择

**Comment by Anartx** [comment]
> @capt-ximao目前应用级别还无法切换系统级别的webview，我网上搜了下升级webview相关的，下面这个教程可以对你有帮助： [Android自带的WebView更新](https://gitee.com/akenclub/android-web-view)
大佬可以参考一下better xcloud，他进去的时候就有个web切换选择
