### ISSUE TITLE
小米电视es65白屏卡死

### ISSUE THREAD

**Issue by xingrenwai** [Geocld/XStreaming#58]
是不是 智能电视 对 xstreaming 有什么权限限制，我也试了装入腾讯极光盒子，也是一模一样的现象，点击串流按钮后，屏幕白屏无反应

确定家里网络没有问题，且xstreaming-desktop版本能完美运行

**Comment by Geocld** [comment]
参考此[问题](https://github.com/Geocld/XStreaming/issues/54)
