### ISSUE TITLE
断开连接耗时过长

### ISSUE THREAD

**Issue by arcsinw** [Geocld/XStreaming#6]
卡在Ice那一步一直连不上，然后后退触发断开连接，这一步要转挺久的进度条，感觉退出可以暴力一点，不需要等这么久

**Comment by arcsinw** [comment]
还有Debug mode的选择好像没持久化下来，选了enable后面再点进选项又变成disable了

**Comment by Geocld** [comment]
@arcsinw 感谢反馈，后续版本会优化这些问题

**Comment by Geocld** [comment]
Fixed in [v1.0.0](https://github.com/Geocld/XStreaming/releases/tag/v1.0.0)
