### ISSUE TITLE
xbox原生手柄震动支持

### ISSUE THREAD

**Issue by momikiii** [Geocld/XStreaming#61]
连接xbox精英手柄后无法震动，请问是需要设置哪些选项？手柄内核、震动模式及覆盖安卓手柄支持等，和手柄相关的设置都试过一遍了，均没有效果

**Comment by Geocld** [comment]
xbox手柄振动协议跟手机系统内核有关，具体参考下图：

![xbox](https://private-user-images.githubusercontent.com/13679095/376419339-d9a533f9-6d38-455e-86cb-664a910974d4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNTY5ODksIm5iZiI6MTczNDA1NjY4OSwicGF0aCI6Ii8xMzY3OTA5NS8zNzY0MTkzMzktZDlhNTMzZjktNmQzOC00NTVlLTg2Y2ItNjY0YTkxMDk3NGQ0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDAyMjQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyY2FjOWExMTIwNjJhZDVmOWJhMmY0ZTUwMzA4NmM2MjZkMDhiN2EzN2RjNWFmMmMyZWJlZjE2YjhmM2NhYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jj4mGbeBcPTDtRzy2rJkEP9OapAvHSDLA_9coYTvRno)

蓝牙振动要求内核最苛刻，可以尝试有线连接。

另外覆盖安卓驱动是有线连接才生效。

**Comment by momikiii** [comment]
刚试了试ps5手柄反而支持震动了😂，另外有上架ios端的打算吗？现在ios端的云游戏方案都不支持手柄震动，如果能解决这个问题，软件收费也得支持下

**Comment by Geocld** [comment]
@momikiii 暂时还没有计划开发iOS版本，可能以后会开发
