### ISSUE TITLE
1.3.0版本登录不了

### ISSUE THREAD

**Issue by zylf00** [Geocld/XStreaming#62]
一直卡在登录成功，正在刷新凭证
挂梯子没用，付费梯子专线节点，其他网站和软件快得很，这个一直这样
挂加速器也没用，uu加速器

**Comment by Geocld** [comment]
@zylf00 最近几个版本都没有对登录逻辑做过调整，登录不上跟软件没有关系，可能跟微软节点有关，请尝试清清空缓存多登录几次。
