### ISSUE TITLE
按下西瓜键无反馈

### ISSUE THREAD

**Issue by TubeLiu** [Geocld/XStreaming#65]
偶发游戏中选择“按下西瓜键”后没有反应。不确定是不是点过“断开连接”后导致的。
另外，选择退出游戏，经常web页面报error code。

**Comment by Geocld** [comment]
@TubeLiu 请提供具体的错误信息和错误代码或截图。

**Comment by TubeLiu** [comment]
https://github.com/user-attachments/assets/0effe42f-b58e-4589-88be-b12d9dd3b4af

**Comment by TubeLiu** [comment]
由于现在按下西瓜键已经没反馈了。所以报错code的那个页面暂时截不到了。

**Comment by Geocld** [comment]
@TubeLiu 这是云游戏，西瓜键本来就不是必须选项，因为服务器不一定提供西瓜键功能，需要退出游戏直接断开连接即可。

**Comment by TubeLiu** [comment]
昨天按下还有反馈的。不知道为什么今天玩所有游戏的时候就都是这样了。

**Comment by Geocld** [comment]
> 昨天按下还有反馈的。不知道为什么今天玩所有游戏的时候就都是这样了。

大概率跟微软的云服务器有关，指令肯定是传过去了，没有反馈也只能是服务器那边出了问题。
