### ISSUE TITLE
原本可以串流但用了加速器无法串流

### ISSUE THREAD

**Issue by kumu112233** [Geocld/XStreaming#66]
使用的是fake后缀的Xstream，原本不用是可以正常串流主机的，但用了之后反而一直显示nat打洞失败。这个怎么解决？

**Comment by kumu112233** [comment]
用5g流量其实也有这个问题，显示nat打洞失败

**Comment by Geocld** [comment]
加速器会自带一层nat导致直连失败，跟软件关系不大。这种情况建议直接使用官方Xbox应用，官方有穿透服务器可以保证任何网络环境都可以连接。
