### ISSUE TITLE
32位4核arm soc也就是电视机顶盒soc有兼容打算吗

### ISSUE THREAD

**Issue by VG666** [Geocld/XStreaming#9]

**Comment by mumiao2000** [comment]
Decoding delay would be intolerant

**Comment by fejich** [comment]
实际上绝大多数安卓电视盒子跟电视机都是 32位的系统

后续应该会有支持的

目前先优化程序的功能

**Comment by backtracker** [comment]
我昨天在小米电视上安装了，可以打开，然后还绑定了微软账号，就在准备串流的时候，怎么也选不到主机，手柄和遥控器都按了，手柄按A就切换tab了。要是能在电视上串流就好了。

**Comment by Geocld** [comment]
暂无计划，电视串流收益太低，现在最重要的是做好移动端的稳定性和功能
